[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "Origins-Bukkit"
authors = [{name = "LemonyPancakes", email = "JiboyJUNE@gmail.com"}]
dynamic = ["version", "description"]
